Instrument blend upload handler
I added some instrumentation to get more information about an
intermittent issue that is causing blend file uploads to fail. Once in a
while, I get an error report via email stating:

InvalidArgumentException: Invalid resource type: resource (closed) in
file [redacted]/vendor/guzzlehttp/psr7/src/functions.php

The stack trace shows this is coming from a call to Guzzle within the
BackblazeB2 SDK during upload.

I'm attempting to get more information about when the resource is
closed.